### ISSUE TITLE
Cucumber report is not getting generated

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina-cucumber#18]
Hi Team,
For the below versions, cucumber reports are not getting generated.
**POM.xml**
        <carina-core_version>7.0.0-beta2-SNAPSHOT</carina-core_version>
        <carina-cucumber_version>1.2-beta2-SNAPSHOT</carina-cucumber_version>
**_config.properties:** 
project_report_directory=reports/qa
report_url=C:/Automation/QA_Automation/reports/qa

**Issue #1:MAJOR**
In a report (file:///C:/Automation/QA_Automation/reports/qa/emailable-report.html) when you click on **Open Cucumber Report in new Window**

It navigates to file:///C:/Automation/QA_Automation/reports/qa/1608016465879/cucumber-reports/cucumber-html-reports/overview-features.html

but it shows error logs:(attaching screenshot1.jpg for reference)
![Screenshot1](https://user-images.githubusercontent.com/31615407/102184298-3c90a280-3ed5-11eb-8447-10ce2eb9cf93.JPG)
 
**Issue #2:MINOR/COSMETIC**
Run results show extra characters like 'Optional'. (attaching screenshot2.jpg for reference)
![Screenshot2](https://user-images.githubusercontent.com/31615407/102184291-3b5f7580-3ed5-11eb-9b47-49f82e989af2.JPG)

**Comment by SergeiZagriychuk** [comment]
Should be fixed in the latest 1.2-beta2-SNAPSHOT
