### ISSUE TITLE
Feature and Scenario Name Value should be present on Zebrunner report 

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina-cucumber#7]
1. Feature and Scenario Name value should be present on the Zebrunner report. 
     Currently, just [Project name - feature] is getting displayed.
2. Results are displayed under reports/qa/unique_id/timestamp
     Instead of timestamp it should be saved as scenario name .

**Comment by SergeiZagriychuk** [comment]
Fixed in 1.2-beta1
No changes needed in test project
