### ISSUE TITLE
Multiple features in parallel run

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina-cucumber#8]
How to run multiple features file in parallel without creating multiple runner files.

**Comment by SergeiZagriychuk** [comment]
You can now manage amount of parallel threads using data provider thread count parameter

How to use: Amount of parallel threads is defined by property data_provider_thread_count in config.properties
Also if qps-pipeline is used then amount of threads may be configured on suite level (using data-provider-thread-count attribute of <suite> tag)
