### ISSUE TITLE
When running a tag from Runner file that contains Examples, driver is not quitting for each example instead it reloads the URL in the same instance for the next one.

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina-cucumber#9]
Suppose there is below feature file
ABC.feature

@tagFeature
feature: <feature description>

@tagScenario
scenario outline: <scenario outline description>
Given statement
When statement
Then statement
Examples:
|Column|
|example1| --> Browser session started for this 
|example2| --> Existing Browser session used here, instead of that new browser session should start as it nothing but new test case with the change in test data.

**Comment by SergeiZagriychuk** [comment]
It should work as expected in 1.2-beta1
